-- ═══════════════════════════════════════════════════════════════════════
--  Row level security, grants, and the seed rows.  VERSION 1
--
--  ── The rule this file exists to enforce ─────────────────────────────
--
--  A browser holds the `anon` key. That key is public by design — it ships inside
--  the JavaScript bundle and is meant to — and it is safe only because of what is
--  written here. So the important number is not "the app has a key" but "the anon
--  role can do almost nothing", and that is what the grants at the bottom check.
--
--  ── No write policies on the money and the loans ─────────────────────
--
--  `loans`, `fines` and `fine_txns` get SELECT and nothing else. No INSERT, no
--  UPDATE, no DELETE — not for `authenticated`, not for anybody.
--
--  Those three tables are written only by the functions in 0002, which check
--  permissions, check the borrow limit, check the balance, and record who did it.
--  This is the difference between "the domain refuses" and "the domain refuses and
--  the database refuses too, if someone bypasses the app".
--
--  ── A view would not have been enough ────────────────────────────────
--
--  If the register were a view over loans, then anyone who could read loans could
--  read the view, and \`SELECT * FROM active_loans\` would be the loans table again
--  rather than a rule. The functions exist because a named query cannot refuse.
--
--  ── What anon may do ─────────────────────────────────────────────────
--
--  Exactly one thing: \`has_any_accounts()\`, so the sign-in screen can tell an empty
--  school from a used one. It returns a boolean and reads no table.
begin;

-- ── RLS on, everywhere ─────────────────────────────────────────────────
-- Named so the list can be compared against the table list in 0001 by the check
-- below. A table added without this would be wide open.

alter table users            enable row level security;
alter table member_types     enable row level security;
alter table members          enable row level security;
alter table titles           enable row level security;
alter table shelf_locations  enable row level security;
alter table copies           enable row level security;
alter table loans            enable row level security;
alter table loan_events      enable row level security;
alter table holds            enable row level security;
alter table fines            enable row level security;
alter table fine_txns        enable row level security;
alter table settings         enable row level security;
alter table imports         enable row level security;
alter table audit            enable row level security;

-- ── Reads ──────────────────────────────────────────────────────────────
-- Every read policy is signed in plus the permission. Not signed in plus nothing:
-- a policy that only checks the permission would pass for a role the function does
-- not know about, and `anonymous` returning false is the safer default.

-- These eleven policies were generated by a plpgsql loop that built each one
-- with format() and a CASE mapping table from table name to permission name. It was
-- clever, and it failed:
--
--   ERROR: 42804: could not determine polymorphic type because input has type unknown
--
-- format() takes VARIADIC "any", so Postgres has to resolve the type of every argument
-- before it can call it, and the CASE feeding it had no ELSE. A CASE with no ELSE
-- returns NULL, and an untyped NULL handed to a polymorphic argument is exactly the
-- error above -- raised at *runtime*, once per loop iteration, with no line number
-- pointing at the cause.
--
-- The same loop had a second fault it never got to: the permission was interpolated
-- with %2$I, which quotes as an SQL identifier, so every policy would have read
--   using (can('"members.read"'))
-- -- a permission string containing literal double quotes. can() compares against
-- 'members.read', so that returns false for every role including admin, and the whole
-- application would have appeared to have no permissions at all.
--
-- Neither is a useful thing to have in the file whose entire job is to decide who may
-- see what. So they are written out. It is more lines and there is nothing left to
-- resolve: no format(), no CASE, no array, no type inference, and the permission for
-- each table is readable next to the table.
--
-- Written the long way on purpose. Obvious beats compact in a security file.
drop policy if exists member_types_read on member_types;
create policy member_types_read on member_types
  for select to authenticated using (can('members.read'));

drop policy if exists members_read on members;
create policy members_read on members
  for select to authenticated using (can('members.read'));

drop policy if exists titles_read on titles;
create policy titles_read on titles
  for select to authenticated using (can('titles.read'));

drop policy if exists shelf_locations_read on shelf_locations;
create policy shelf_locations_read on shelf_locations
  for select to authenticated using (can('copies.read'));

drop policy if exists copies_read on copies;
create policy copies_read on copies
  for select to authenticated using (can('copies.read'));

drop policy if exists loans_read on loans;
create policy loans_read on loans
  for select to authenticated using (can('loans.read'));

-- loan_events is readable wherever the loan is: it is the loan's own history, and
-- denying it while allowing loans.read would show a loan with no explanation of how it
-- got that way.
drop policy if exists loan_events_read on loan_events;
create policy loan_events_read on loan_events
  for select to authenticated using (can('loans.read'));

drop policy if exists holds_read on holds;
create policy holds_read on holds
  for select to authenticated using (can('holds.read'));

drop policy if exists fines_read on fines;
create policy fines_read on fines
  for select to authenticated using (can('fines.read'));

-- The ledger is readable exactly when the fine is. Splitting them would let somebody
-- see that money changed without being able to see why, which is worse than seeing
-- neither.
drop policy if exists fine_txns_read on fine_txns;
create policy fine_txns_read on fine_txns
  for select to authenticated using (can('fines.read'));

drop policy if exists settings_read on settings;
create policy settings_read on settings
  for select to authenticated using (can('settings.read'));

-- Accounts. Readable by anyone signed in — a librarian needs to see who else can
-- sign in — but the policies still route through `can`, so a teacher gets nothing.
drop policy if exists users_read on users;
create policy users_read on users
  for select to authenticated using (can('users.read'));

drop policy if exists users_insert on users;
create policy users_insert on users
  for insert to authenticated with check (can('users.write'));

drop policy if exists users_update on users;
create policy users_update on users
  for update to authenticated
  using (can('users.write')) with check (can('users.write'));

drop policy if exists audit_read on audit;
create policy audit_read on audit
  for select to authenticated using (can('audit.read'));

drop policy if exists audit_insert on audit;
create policy audit_insert on audit
  for insert to authenticated with check (actor = current_user_id());

-- ── Writes, where a policy is enough ───────────────────────────────────
-- These are edits to records rather than movements of money, so a checked policy
-- is proportionate: the policy decides, and the row is then ordinary data.

-- Written out rather than generated, for the same reasons as the read policies above,
-- and carrying the same two faults this loop had: a CASE with no ELSE feeding format()'s
-- polymorphic argument, and %2$I quoting the permission as an identifier so the policy
-- would have compared against '"members.write"'. Since members and holds are the only
-- two distinct permissions here, the loop was never buying much.
drop policy if exists members_update on members;
create policy members_update on members
  for update to authenticated
  using (can('members.write')) with check (can('members.write'));

drop policy if exists titles_update on titles;
create policy titles_update on titles
  for update to authenticated
  using (can('titles.write')) with check (can('titles.write'));

drop policy if exists copies_update on copies;
create policy copies_update on copies
  for update to authenticated
  using (can('copies.write')) with check (can('copies.write'));

-- holds is writable by holds.write alone. Somebody who can fill a hold queue does not
-- thereby gain the ability to edit books or people.
drop policy if exists holds_update on holds;
create policy holds_update on holds
  for update to authenticated
  using (can('holds.write')) with check (can('holds.write'));

-- Settings and imports: administrators only, and both directions.
drop policy if exists settings_write on settings;
create policy settings_write on settings
  for all to authenticated
  using (can('settings.write')) with check (can('settings.write'));

drop policy if exists imports_write on imports;
create policy imports_write on imports
  for all to authenticated
  using (can('imports.run')) with check (can('imports.run'));

-- Members and titles can be created. The insert paths are separate from the update
-- ones because a policy with no `for` clause defaults to `all`, and an `all`
-- policy on members would grant deletes — and deleting a student who has borrowing
-- history is not something this system should be able to do at all.
drop policy if exists members_insert on members;
create policy members_insert on members
  for insert to authenticated with check (can('members.write'));

drop policy if exists titles_insert on titles;
create policy titles_insert on titles
  for insert to authenticated with check (can('titles.write'));

drop policy if exists copies_insert on copies;
create policy copies_insert on copies
  for insert to authenticated with check (can('copies.write'));

drop policy if exists holds_insert on holds;
create policy holds_insert on holds
  for insert to authenticated with check (can('holds.write'));

drop policy if exists holds_update on holds;
create policy holds_update on holds
  for update to authenticated
  using (can('holds.write')) with check (can('holds.write'));

-- ── No delete policies, anywhere, on purpose ───────────────────────────
-- A delete is not something this system can do. A loan is voided, a fine is waived,
-- a student is graduated, a book is withdrawn: every one of those leaves the record
-- standing with a reason attached. Nothing is removed, so no table gets a DELETE
-- policy and none is granted below.

-- ── The one thing anon may call ────────────────────────────────────────
--
-- The sign-in screen has to tell an empty school from a used one, and it has to do
-- so before anybody has signed in. This returns a boolean and reads no table, so it
-- tells an unauthenticated visitor that accounts exist without telling them who.

create or replace function has_any_accounts()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from users);
$$;

comment on function has_any_accounts() is
  'Whether any account exists. Callable by anon so the sign-in screen can offer setup instead of sign-in.';

-- ── Grants ─────────────────────────────────────────────────────────────

-- anon: nothing at all on any table. Not "read public rows", not "read nothing" —
--  no privilege of any kind.
--
-- `ON ALL <thing> IN SCHEMA public` is the whole syntax. The `IN SCHEMA` clause is not
-- optional: `REVOKE ALL ON ALL TABLES FROM anon` is MySQL's spelling and Postgres
-- rejects it with `syntax error at or near "from"`. Without a schema there is nothing
-- for `ALL` to range over, and naming a schema is also what keeps this from reaching
-- into extensions or other schemas that were never meant to be exposed.
--
-- `IN SCHEMA public` rather than a bare `IN SCHEMA`: that form takes a schema list, and
-- a single name is not a list.
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all routines  in schema public from anon;

grant execute on function has_any_accounts() to anon;

-- authenticated: the table privileges the policies above then narrow.
grant select on users, member_types, members, titles, shelf_locations, copies,
              loans, loan_events, holds, fines, fine_txns, settings, imports, audit
  to authenticated;

grant insert, update on users, member_types, members, titles, shelf_locations,
                           copies, holds, settings, imports
  to authenticated;

-- The three that are written only by functions. SELECT is a privilege; the ability
-- to change a row is not granted at all, so the absence of a policy above is not the
-- only thing standing between a signed-in user and a forged loan.
grant update on member_types, settings to authenticated;

revoke insert, update, delete on loans    from authenticated;
revoke insert, update, delete on fines    from authenticated;
revoke insert, update, delete on fine_txns from authenticated;
revoke insert, update, delete on loan_events from authenticated;
revoke delete on members, titles, copies, holds, imports, audit from authenticated;

-- The functions are how circulation happens, so every signed-in account may call
-- them. Each one checks its own permission first, and that is the check that matters: the
-- GRANT only decides whether a call reaches the function, and the function decides
-- whether it does anything.
--
-- One statement per function, each with its full argument-type signature. Both of those
-- are required rather than stylistic:
--
--   GRANT EXECUTE ON FUNCTION a, b, c TO authenticated    -- not valid Postgres
--   GRANT EXECUTE ON FUNCTION can TO authenticated        -- matches nothing, silently
--
-- The first is a syntax error. The second is worse: a grant naming a function wrongly
-- does not error, it grants nothing, and the symptom is a librarian pressing a button
-- that does nothing. The signature is also what separates 'can' from 'can(text)' --
-- Postgres permits the overload, so a bare name is ambiguous.
--
-- This was a loop and the loop failed twice with
--
--   ERROR: 42804: could not determine polymorphic type because input has type unknown
--
-- format() is format(text, VARIADIC "any"), so Postgres resolves the type of every
-- argument before it can call it, and FOREACH ... IN ARRAY goes through
-- array_lower/array_upper, which are polymorphic too. Casting the array fixed the cast
-- and not the call, and chasing that was the wrong answer to the second failure. The
-- right answer was to stop being clever in the file that decides who may read the
-- register.
--
-- So the loop is gone, and with it the whole class of fault rather than one instance of
-- it: there is no format(), no FOREACH and no type inference left in this file.
--
-- Signatures read out of 0001 and 0002 by tools/print-signatures.mjs rather than typed
-- from memory. 'integer' is Postgres's own spelling of 'int'.
grant execute on function current_user_id() to authenticated;
grant execute on function current_role_name() to authenticated;
grant execute on function can(text) to authenticated;
grant execute on function borrow_blockers(text, text) to authenticated;
grant execute on function issue_book(text, text, timestamptz, timestamptz, boolean, text) to authenticated;
grant execute on function return_book(uuid, copy_condition, timestamptz, boolean) to authenticated;
grant execute on function renew_loan(uuid, boolean, text) to authenticated;
grant execute on function void_loan(uuid, text) to authenticated;
grant execute on function mark_lost(uuid, text) to authenticated;
grant execute on function record_payment(uuid, integer, text) to authenticated;
grant execute on function waive_fine(uuid, text) to authenticated;
grant execute on function recompute_fine_balance(uuid) to authenticated;
grant execute on function run_fine_accrual(timestamptz) to authenticated;

-- ── Seed ───────────────────────────────────────────────────────────────
--
-- The member types and the settings that packages/contracts and
-- apps/web/src/api/mock.ts also carry. Two copies of the school's policy, and the
-- database one is the one that is enforced.

insert into member_types
  (key, label, loan_period_days, grace_days, max_renewals, borrow_limit,
   can_place_holds, fine_exempt, fine_block_threshold, sort_order)
values
  ('student',  'Student',  14, 1, 2,  5, true, false, 1500, 0),
  ('teacher',  'Teacher',  30, 1, 4, 25, true, true,     0, 1),
  ('staff',    'Staff',    14, 1, 2,  5, true, false, 1500, 2),
  ('external', 'External',  7, 0, 0,  2, true, false, 1500, 3)
on conflict (key) do nothing;

insert into settings (key, value) values
  -- 25 cents a day, in cents, because every money column is an integer.
  ('fine.defaultDailyRateCents', to_jsonb(25)),
  ('fine.maxPerFineCents',       to_jsonb(2000)),
  ('school.name',                to_jsonb('Dandora Secondary School'))
on conflict (key) do nothing;

-- No accounts are seeded. The first librarian is created through the sign-in screen,
-- and `create_first_user` below is the only way that can happen — so there is no
-- default password sitting in a public repository.

create or replace function create_first_user(p_email text, p_name text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if exists (select 1 from users) then
    return jsonb_build_object('ok', false, 'code', 'already_set_up',
      'message', 'This library already has an account. Sign in instead.');
  end if;

  insert into users (email, name, role, status)
  values (lower(btrim(p_email)), btrim(p_name), 'admin', 'active')
  returning id into v_id;

  return jsonb_build_object('ok', true, 'id', v_id, 'role', 'admin');
end
$$;

comment on function create_first_user(text, text, text) is
  'Creates the one administrator, and only if none exists. p_password is accepted and ignored: passwords are Supabase Auth''s business, not this schema''s.';

grant execute on function create_first_user(text, text, text) to anon, authenticated;

commit;

-- ── What this file leaves out, and why ─────────────────────────────────
--
-- No `loans_insert`. No `fines_insert`. No `fine_txns_insert`.
--
-- That is the point of the whole file. A loan is created by calling issue_book,
-- which checks the borrow limit, the fine balance, the copy's status and the
-- caller's permission, and records who did it. There is no other door, and no
-- `anon` key can open it — because there are no anon privileges on any table to
-- begin with.